title: Peter Ojo
logo: Head shot.JPG
description: With about 2 years of experience in data analysis, I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
